// DECK 1
export const Deck1 = [
    // Terrenos (20)
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },

    // Equipamentos (8)
    { url: 'Images/Cartas/EspadaDeRaja.png', type: 'equipamento' },
    { url: 'Images/Cartas/EspadaDeRaja.png', type: 'equipamento' },
    { url: 'Images/Cartas/EscudoTigre.png', type: 'equipamento' },
    { url: 'Images/Cartas/EscudoTigre.png', type: 'equipamento' },
    { url: 'Images/Cartas/EspadaAbyssal.png', type: 'equipamento' },
    { url: 'Images/Cartas/EspadaAbyssal.png', type: 'equipamento' },
    { url: 'Images/Cartas/AguaViva.png', type: 'equipamento' },
    { url: 'Images/Cartas/AguaViva.png', type: 'equipamento' },

    // Criaturas (32)
    { url: 'Images/Cartas/AtumKotok.png', type: 'criatura' },
    { url: 'Images/Cartas/AtumKotok.png', type: 'criatura' },
    { url: 'Images/Cartas/AtumKotok.png', type: 'criatura' },
    { url: 'Images/Cartas/OMaiorEspadaAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/OMaiorEspadaAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/OMaiorEspadaAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/XamaCoraisRaja.png', type: 'criatura' },
    { url: 'Images/Cartas/XamaCoraisRaja.png', type: 'criatura' },
    { url: 'Images/Cartas/XamaCoraisRaja.png', type: 'criatura' },
    { url: 'Images/Cartas/EspadaTempestades.png', type: 'criatura' },
    { url: 'Images/Cartas/EspadaTempestades.png', type: 'criatura' },
    { url: 'Images/Cartas/EspadaTempestades.png', type: 'criatura' },
    { url: 'Images/Cartas/InvocadorDaTempestade.png', type: 'criatura' },
    { url: 'Images/Cartas/InvocadorDaTempestade.png', type: 'criatura' },
    { url: 'Images/Cartas/InvocadorDaTempestade.png', type: 'criatura' },
    { url: 'Images/Cartas/GaroupaAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas/GaroupaAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas/GaroupaAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas/ImperadorAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/ImperadorAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/ImperadorAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/TainhaRelampago.png', type: 'criatura' },
    { url: 'Images/Cartas/TainhaRelampago.png', type: 'criatura' },
    { url: 'Images/Cartas/TainhaRelampago.png', type: 'criatura' },
    { url: 'Images/Cartas/FeiticeiroDeMaluk.png', type: 'criatura' },
    { url: 'Images/Cartas/FeiticeiroDeMaluk.png', type: 'criatura' },
    { url: 'Images/Cartas/FeiticeiroDeMaluk.png', type: 'criatura' },
    { url: 'Images/Cartas/Tentopolus.png', type: 'criatura' },
    { url: 'Images/Cartas/Tentopolus.png', type: 'criatura' },
    { url: 'Images/Cartas/Tentopolus.png', type: 'criatura' },
    { url: 'Images/Cartas/SororocaEletrica.png', type: 'criatura' },
    { url: 'Images/Cartas/SororocaEletrica.png', type: 'criatura' },
    { url: 'Images/Cartas/SororocaEletrica.png', type: 'criatura' }
];

// DECK 2
export const Deck2 = [
    // Terrenos (20 cartas)
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },

    // Equipamentos (8 cartas)
    { url: 'Images/Cartas2/CoraisSumba.png', type: 'equipamento' },
    { url: 'Images/Cartas2/CoraisSumba.png', type: 'equipamento' },
    { url: 'Images/Cartas2/EspinhaAbyssal.png', type: 'equipamento' },
    { url: 'Images/Cartas2/EspinhaAbyssal.png', type: 'equipamento' },
    { url: 'Images/Cartas2/TravasDeArrasto.png', type: 'equipamento' },
    { url: 'Images/Cartas2/TravasDeArrasto.png', type: 'equipamento' },
    { url: 'Images/Cartas2/TridenteKomodo.png', type: 'equipamento' },
    { url: 'Images/Cartas2/TridenteKomodo.png', type: 'equipamento' },

    // Criaturas (32 cartas)
    { url: 'Images/Cartas2/BaleiasPiloto.png', type: 'criatura' },
    { url: 'Images/Cartas2/BaleiasPiloto.png', type: 'criatura' },
    { url: 'Images/Cartas2/BaleiasPiloto.png', type: 'criatura' },
    { url: 'Images/Cartas2/BaleiasPiloto.png', type: 'criatura' },
    { url: 'Images/Cartas2/ColossalDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ColossalDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ColossalDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ForasteiroLunar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ForasteiroLunar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ForasteiroLunar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ForasteiroLunar.png', type: 'criatura' },
    { url: 'Images/Cartas2/GuardiaoDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/GuardiaoDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/MarteloEletrico.png', type: 'criatura' },
    { url: 'Images/Cartas2/MarteloEletrico.png', type: 'criatura' },
    { url: 'Images/Cartas2/MarteloEletrico.png', type: 'criatura' },
    { url: 'Images/Cartas2/MarteloEletrico.png', type: 'criatura' },
    { url: 'Images/Cartas2/TigreKrakatoa.png', type: 'criatura' },
    { url: 'Images/Cartas2/TigreKrakatoa.png', type: 'criatura' },
    { url: 'Images/Cartas2/TigreKrakatoa.png', type: 'criatura' },
    { url: 'Images/Cartas2/TigreKrakatoa.png', type: 'criatura' },
    { url: 'Images/Cartas2/PrincipeAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas2/PrincipeAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas2/PrincipeAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas2/PrincipeAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas2/TubaraoCelestial.png', type: 'criatura' },
    { url: 'Images/Cartas2/TubaraoCelestial.png', type: 'criatura' },
    { url: 'Images/Cartas2/TubaraoCelestial.png', type: 'criatura' },
    { url: 'Images/Cartas2/TubaraoCelestial.png', type: 'criatura' },
    { url: 'Images/Cartas2/Komodo.png', type: 'criatura' },
    { url: 'Images/Cartas2/Komodo.png', type: 'criatura' },
    { url: 'Images/Cartas2/Komodo.png', type: 'criatura' },
];