// DECK 1
export const Deck1 = [
    // Terrenos (20)
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/Kotok.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/IlhaMaluk.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },
    { url: 'Images/Cartas/ArquipelogoTrovão.png', type: 'terreno' },

    // Equipamentos (8)
    { url: 'Images/Cartas/EspadaDeRaja.png', type: 'equipamento' },
    { url: 'Images/Cartas/EspadaDeRaja.png', type: 'equipamento' },
    { url: 'Images/Cartas/EscudoTigre.png', type: 'equipamento' },
    { url: 'Images/Cartas/EscudoTigre.png', type: 'equipamento' },
    { url: 'Images/Cartas/EspadaAbyssal.png', type: 'equipamento' },
    { url: 'Images/Cartas/EspadaAbyssal.png', type: 'equipamento' },
    { url: 'Images/Cartas/AguaViva.png', type: 'equipamento' },
    { url: 'Images/Cartas/AguaViva.png', type: 'equipamento' },

    // Criaturas (32)
    { url: 'Images/Cartas/AtumKotok.png', type: 'criatura' },
    { url: 'Images/Cartas/AtumKotok.png', type: 'criatura' },
    { url: 'Images/Cartas/AtumKotok.png', type: 'criatura' },
    { url: 'Images/Cartas/OMaiorEspadaAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/OMaiorEspadaAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/OMaiorEspadaAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/XamaCoraisRaja.png', type: 'criatura' },
    { url: 'Images/Cartas/XamaCoraisRaja.png', type: 'criatura' },
    { url: 'Images/Cartas/XamaCoraisRaja.png', type: 'criatura' },
    { url: 'Images/Cartas/EspadaTempestades.png', type: 'criatura' },
    { url: 'Images/Cartas/EspadaTempestades.png', type: 'criatura' },
    { url: 'Images/Cartas/EspadaTempestades.png', type: 'criatura' },
    { url: 'Images/Cartas/InvocadorDaTempestade.png', type: 'criatura' },
    { url: 'Images/Cartas/InvocadorDaTempestade.png', type: 'criatura' },
    { url: 'Images/Cartas/InvocadorDaTempestade.png', type: 'criatura' },
    { url: 'Images/Cartas/GaroupaAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas/GaroupaAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas/GaroupaAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas/ImperadorAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/ImperadorAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/ImperadorAbyssal.png', type: 'criatura' },
    { url: 'Images/Cartas/TainhaRelampago.png', type: 'criatura' },
    { url: 'Images/Cartas/TainhaRelampago.png', type: 'criatura' },
    { url: 'Images/Cartas/TainhaRelampago.png', type: 'criatura' },
    { url: 'Images/Cartas/FeiticeiroDeMaluk.png', type: 'criatura' },
    { url: 'Images/Cartas/FeiticeiroDeMaluk.png', type: 'criatura' },
    { url: 'Images/Cartas/FeiticeiroDeMaluk.png', type: 'criatura' },
    { url: 'Images/Cartas/Tentopolus.png', type: 'criatura' },
    { url: 'Images/Cartas/Tentopolus.png', type: 'criatura' },
    { url: 'Images/Cartas/Tentopolus.png', type: 'criatura' },
    { url: 'Images/Cartas/SororocaEletrica.png', type: 'criatura' },
    { url: 'Images/Cartas/SororocaEletrica.png', type: 'criatura' },
    { url: 'Images/Cartas/SororocaEletrica.png', type: 'criatura' }
];

// DECK 2
export const Deck2 = [
    // Terrenos (20 cartas)
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },
    { url: 'Images/Cartas2/ImperioSumba.png', type: 'terreno' },
    { url: 'Images/Cartas2/IlhasKrakatoa.png', type: 'terreno' },
    { url: 'Images/Cartas2/AtolPadar.png', type: 'terreno' },

    // Equipamentos (8 cartas)
    { url: 'Images/Cartas2/CoraisSumba.png', type: 'equipamento' },
    { url: 'Images/Cartas2/CoraisSumba.png', type: 'equipamento' },
    { url: 'Images/Cartas2/EspinhaAbyssal.png', type: 'equipamento' },
    { url: 'Images/Cartas2/EspinhaAbyssal.png', type: 'equipamento' },
    { url: 'Images/Cartas2/TravasDeArrasto.png', type: 'equipamento' },
    { url: 'Images/Cartas2/TravasDeArrasto.png', type: 'equipamento' },
    { url: 'Images/Cartas2/TridenteKomodo.png', type: 'equipamento' },
    { url: 'Images/Cartas2/TridenteKomodo.png', type: 'equipamento' },

    // Criaturas (32 cartas)
    { url: 'Images/Cartas2/BaleiasPiloto.png', type: 'criatura' },
    { url: 'Images/Cartas2/BaleiasPiloto.png', type: 'criatura' },
    { url: 'Images/Cartas2/BaleiasPiloto.png', type: 'criatura' },
    { url: 'Images/Cartas2/BaleiasPiloto.png', type: 'criatura' },
    { url: 'Images/Cartas2/ColossalDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ColossalDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ColossalDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ForasteiroLunar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ForasteiroLunar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ForasteiroLunar.png', type: 'criatura' },
    { url: 'Images/Cartas2/ForasteiroLunar.png', type: 'criatura' },
    { url: 'Images/Cartas2/GuardiaoDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/GuardiaoDePadar.png', type: 'criatura' },
    { url: 'Images/Cartas2/MarteloEletrico.png', type: 'criatura' },
    { url: 'Images/Cartas2/MarteloEletrico.png', type: 'criatura' },
    { url: 'Images/Cartas2/MarteloEletrico.png', type: 'criatura' },
    { url: 'Images/Cartas2/MarteloEletrico.png', type: 'criatura' },
    { url: 'Images/Cartas2/TigreKrakatoa.png', type: 'criatura' },
    { url: 'Images/Cartas2/TigreKrakatoa.png', type: 'criatura' },
    { url: 'Images/Cartas2/TigreKrakatoa.png', type: 'criatura' },
    { url: 'Images/Cartas2/TigreKrakatoa.png', type: 'criatura' },
    { url: 'Images/Cartas2/PrincipeAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas2/PrincipeAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas2/PrincipeAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas2/PrincipeAncestral.png', type: 'criatura' },
    { url: 'Images/Cartas2/TubaraoCelestial.png', type: 'criatura' },
    { url: 'Images/Cartas2/TubaraoCelestial.png', type: 'criatura' },
    { url: 'Images/Cartas2/TubaraoCelestial.png', type: 'criatura' },
    { url: 'Images/Cartas2/TubaraoCelestial.png', type: 'criatura' },
    { url: 'Images/Cartas2/Komodo.png', type: 'criatura' },
    { url: 'Images/Cartas2/Komodo.png', type: 'criatura' },
    { url: 'Images/Cartas2/Komodo.png', type: 'criatura' },
];

//DECK 3
export const Deck3 = [
    // Terrenos (20 cartas)
    { url: 'Images/Cartas3/BarganhaDosCavaleiros.png', type: 'terreno' },
    { url: 'Images/Cartas3/BarganhaDosCavaleiros.png', type: 'terreno' },
    { url: 'Images/Cartas3/BarganhaDosCavaleiros.png', type: 'terreno' },
    { url: 'Images/Cartas3/FrotaRealAbandonada.png', type: 'terreno' },
    { url: 'Images/Cartas3/FrotaRealAbandonada.png', type: 'terreno' },
    { url: 'Images/Cartas3/FrotaRealAbandonada.png', type: 'terreno' },
    { url: 'Images/Cartas3/TormentaDeSkull.png', type: 'terreno' },
    { url: 'Images/Cartas3/TormentaDeSkull.png', type: 'terreno' },
    { url: 'Images/Cartas3/TormentaDeSkull.png', type: 'terreno' },
    { url: 'Images/Cartas3/BarganhaDosCavaleiros.png', type: 'terreno' },
    { url: 'Images/Cartas3/FrotaRealAbandonada.png', type: 'terreno' },
    { url: 'Images/Cartas3/TormentaDeSkull.png', type: 'terreno' },
    { url: 'Images/Cartas3/BarganhaDosCavaleiros.png', type: 'terreno' },
    { url: 'Images/Cartas3/FrotaRealAbandonada.png', type: 'terreno' },
    { url: 'Images/Cartas3/TormentaDeSkull.png', type: 'terreno' },
    { url: 'Images/Cartas3/BarganhaDosCavaleiros.png', type: 'terreno' },
    { url: 'Images/Cartas3/FrotaRealAbandonada.png', type: 'terreno' },
    { url: 'Images/Cartas3/TormentaDeSkull.png', type: 'terreno' },
    { url: 'Images/Cartas3/BarganhaDosCavaleiros.png', type: 'terreno' },
    { url: 'Images/Cartas3/FrotaRealAbandonada.png', type: 'terreno' },

    // Equipamentos (6 cartas)
    { url: 'Images/Cartas3/AguaDaVida.png', type: 'equipamento' },
    { url: 'Images/Cartas3/AguaDaVida.png', type: 'equipamento' },
    { url: 'Images/Cartas3/FileteiraNegra.png', type: 'equipamento' },
    { url: 'Images/Cartas3/FileteiraNegra.png', type: 'equipamento' },
    { url: 'Images/Cartas3/PerolaEnfeiticada.png', type: 'equipamento' },
    { url: 'Images/Cartas3/PerolaEnfeiticada.png', type: 'equipamento' },

    // Feitiços (4 cartas)
    { url: 'Images/Cartas3/EncantoDeSkull.png', type: 'feitiço' },
    { url: 'Images/Cartas3/EncantoDeSkull.png', type: 'feitiço' },
    { url: 'Images/Cartas3/PalacioPerdido.png', type: 'feitiço' },
    { url: 'Images/Cartas3/PalacioPerdido.png', type: 'feitiço' },

    // Criaturas (30 cartas)
    { url: 'Images/Cartas3/Bakara.png', type: 'criatura' },
    { url: 'Images/Cartas3/Bakara.png', type: 'criatura' },
    { url: 'Images/Cartas3/Braven.png', type: 'criatura' },
    { url: 'Images/Cartas3/Braven.png', type: 'criatura' },
    { url: 'Images/Cartas3/ElenoraRainha.png', type: 'criatura' },
    { url: 'Images/Cartas3/ElenoraRainha.png', type: 'criatura' },
    { url: 'Images/Cartas3/JackfeiticoPerola.png', type: 'criatura' },
    { url: 'Images/Cartas3/JackfeiticoPerola.png', type: 'criatura' },
    { url: 'Images/Cartas3/OrcPirataSkull.png', type: 'criatura' },
    { url: 'Images/Cartas3/OrcPirataSkull.png', type: 'criatura' },
    { url: 'Images/Cartas3/PirataAmaldicoada.png', type: 'criatura' },
    { url: 'Images/Cartas3/PirataAmaldicoada.png', type: 'criatura' },
    { url: 'Images/Cartas3/RainhaReal.png', type: 'criatura' },
    { url: 'Images/Cartas3/RainhaReal.png', type: 'criatura' },
    { url: 'Images/Cartas3/SumatraGeneralOrc.png', type: 'criatura' },
    { url: 'Images/Cartas3/SumatraGeneralOrc.png', type: 'criatura' },
    { url: 'Images/Cartas3/Bakara.png', type: 'criatura' },
    { url: 'Images/Cartas3/Braven.png', type: 'criatura' },
    { url: 'Images/Cartas3/ElenoraRainha.png', type: 'criatura' },
    { url: 'Images/Cartas3/JackfeiticoPerola.png', type: 'criatura' },
    { url: 'Images/Cartas3/OrcPirataSkull.png', type: 'criatura' },
    { url: 'Images/Cartas3/PirataAmaldicoada.png', type: 'criatura' },
    { url: 'Images/Cartas3/RainhaReal.png', type: 'criatura' },
    { url: 'Images/Cartas3/SumatraGeneralOrc.png', type: 'criatura' },
    { url: 'Images/Cartas3/Bakara.png', type: 'criatura' },
    { url: 'Images/Cartas3/Braven.png', type: 'criatura' },
    { url: 'Images/Cartas3/ElenoraRainha.png', type: 'criatura' },
    { url: 'Images/Cartas3/JackfeiticoPerola.png', type: 'criatura' },
    { url: 'Images/Cartas3/OrcPirataSkull.png', type: 'criatura' },
    { url: 'Images/Cartas3/PirataAmaldicoada.png', type: 'criatura' },
    { url: 'Images/Cartas3/RainhaReal.png', type: 'criatura' },
    { url: 'Images/Cartas3/SumatraGeneralOrc.png', type: 'criatura' }
];
